; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy40  ; 普段使う方を指定

; --- Teensy 4.0 用 (600MHzの怪物) ---
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
build_flags = -D USE_TEENSY

; --- XIAO RP2040 用 ---
[env:seeed_xiao_rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino

; --- Arduino Uno 用 ---
[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -D USE_UNO

[env]
lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14

monitor_filters = direct